apiVersion: batch/v1
kind: Job
metadata:
  name: arc-demo-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl-healthz
          image: curlimages/curl:8.10.1
          args:
            - "-fsS"
            - "http://arc-demo.default.svc.cluster.local:8000/healthz"
  backoffLimit: 1
